[project]
name = "streamlit-chat-ui"
version = "0.1.0"
description = "Streamlit chat UI scaffold"
requires-python = ">=3.13"

dependencies = [
    "streamlit==1.36.0",
    "watchdog>=4.0.2",
]

[tool.uv]
# Optional: pinning index or cache settings goes here
